[package]
name = "AxelarGateway"
version = "0.1.0"
edition = "2024"
published-at = "0xeb055ffc3237c24e305a2bb760fe6551f6ff7c5fdb68735169c0f528fccab373"

[dependencies]
[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet-v1.38.3"

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/move-stdlib"
rev = "mainnet-v1.38.3"

[dependencies.VersionControl]
git = "https://github.com/aadish02/axelar-cgp-sui.git"
subdir = "move/version_control"
rev = "v1.0.0"

[dependencies.Utils]
git = "https://github.com/aadish02/axelar-cgp-sui.git"
subdir = "move/utils"
rev = "v1.0.0"

[addresses]
axelar_gateway = "0xeb055ffc3237c24e305a2bb760fe6551f6ff7c5fdb68735169c0f528fccab373"
clock = "0x6"